AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "docs/**/*"

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  # Standard gem pattern: list dev tools in the gemspec.
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/ParameterLists:
  Exclude:
    - "lib/race_guard/event.rb"

Metrics/ClassLength:
  Exclude:
    - "lib/race_guard/configuration.rb"

Metrics/MethodLength:
  Max: 12
